[tool.poetry]
name = "pop-down-gym"
version = "0.1.0"
description = ""
authors = ["Allen Wang <allenw@mit.edu>"]
readme = "README.md"
packages = [{include = "pop_down_gym"}]

[tool.poetry.dependencies]
python = ">=3.9, <3.10"
scipy = "^1.10.1"
pytest = "^7.4.0"
jaxlib = {version = "^0.4.14+cuda12.cudnn89", source = "jax_cuda"}
jax = {extras = ["cuda12-pip"], version = "^0.4.20"}
gymnasium = "0.28.1"
contrax = { path = "contrax/", develop = true }
debugpy = "1.6.7"
black = "^23.7.0"
wandb = "0.15.4"
plotly = "^5.16.1"
stable-baselines3 = "2.0.0a10"
tensorboard = "^2.14.0"
urllib3 = "1.26.16"
seaborn = "^0.13.0"

[[tool.poetry.source]]
name = "jax_cuda"
url = "https://storage.googleapis.com/jax-releases/jax_cuda_releases.html"
priority = "primary"


[tool.poetry.group.dev.dependencies]
black = "^23.10.1"
isort = "^5.12.0"
pytest = "^7.4.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
addopts = "--ignore pop_down_gym/raptor --ignore contrax"

[tool.black]
# 'extend-exclude' excludes files or directories in addition to the defaults
extend-exclude = """
(
    .*contrax.*
    |.*raptor.*
)
"""