from typing import Union

import gymnasium as gym
import pandas as pd
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from stable_baselines3.common.callbacks import BaseCallback
from stable_baselines3.common.evaluation import evaluate_policy

import wandb


def df_to_plotly_fig(df, title):
    n_vars = len(df.columns)
    fig = make_subplots(
        rows=n_vars, cols=1, shared_xaxes=True, subplot_titles=df.columns
    )
    for i, column in enumerate(df.columns):
        fig.add_trace(
            go.Scatter(x=df.index, y=df[column], name=column), row=i + 1, col=1
        )
    fig.update_layout(title=title)
    fig.update_layout(autosize=False, height=n_vars * 800, width=800)
    return fig


def generate_reward_input_plots(r_inputs_df, limits):
    fig = df_to_plotly_fig(r_inputs_df, "Reward Inputs")
    for i in range(len(r_inputs_df.columns)):
        variable_name = r_inputs_df.columns[i]
        if variable_name in limits:
            limit = limits[variable_name]
            fig.add_hline(y=limit, row=i + 1, col=1, line_dash="dash", line_color="red")
    return fig


def infos_to_plots(infos, limits):
    """
    Given a list of infos generated by the training environment,
    create plotly plots to visualize the results.
    """
    times = [info["time"] for info in infos]
    states = [info["state"] for info in infos]
    r_inputs = [info["reward_inputs"] for info in infos]
    actions = [info["action"] for info in infos]
    reward_terms = [info["reward_terms"] for info in infos]

    states_df = pd.DataFrame(data=states, index=times)
    r_inputs_df = pd.DataFrame(data=r_inputs, index=times)
    actions_df = pd.DataFrame(data=actions, index=times)
    reward_terms_df = pd.DataFrame(data=reward_terms, index=times)

    states_fig = df_to_plotly_fig(states_df, "States")
    r_inputs_fig = generate_reward_input_plots(r_inputs_df, limits)
    actions_fig = df_to_plotly_fig(actions_df, "Actions")
    reward_terms_fig = df_to_plotly_fig(reward_terms_df, "Reward Terms")

    figure_dic = {
        "states": states_fig,
        "reward_inputs": r_inputs_fig,
        "actions": actions_fig,
        "reward_terms": reward_terms_fig,
    }
    return figure_dic


class VisualizeEval(BaseCallback):
    def __init__(
        self,
        eval_env: gym.Env,
        limits,
        run: Union[wandb.run, None],
        n_eval_episodes: int = 1,
        deterministic: bool = True,
    ):
        super().__init__()
        self._eval_env = eval_env
        self.run = run
        self._n_eval_episodes = n_eval_episodes
        self._deterministic = deterministic
        self.limits = limits

    def _on_step(self) -> bool:
        infos = []

        def get_info_dicts(_locals, _globals) -> None:
            infos.append(_locals["info"])

        evaluate_policy(
            self.model,
            self._eval_env,
            callback=get_info_dicts,
            n_eval_episodes=self._n_eval_episodes,
            deterministic=self._deterministic,
        )

        figure_dic = infos_to_plots(infos, self.limits)

        if self.run:
            self.run.log(figure_dic)
        return figure_dic
